repos:
  - repo: https://github.com/terraform-docs/terraform-docs
    rev: "v0.16.0"
    hooks:
      - id: terraform-docs-go
        args: ["markdown", "table", "--output-file", "README.md", "./"]

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: "v1.79.1"
    hooks:
      - id: terraform_fmt
      - id: terraform_providers_lock
      - id: checkov
      - id: terraform_tfsec
      - id: terraform init
      - id: terraform_validate
      - id: terraform_tflint
      - id: infracost_breakdown
        args:
         - --args=--path=.
        verbose: true
