---
# .github/workflows/init.yaml
name: Terraform - init
run-name: '[${{ github.event_name }} - ${{ github.ref_name }}] Terraform executed by @${{ github.actor }}'

on:
  push:
    branches:
      - main
      - DEVOPS-6-FIXES


env:
  terraformVersion: 1.4.0
  terraformWorkDir: ./terraform
  terraformModulesGithubOrg: terraform-aws-module-template
  awsRegion: us-east-1

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.terraformVersion }}

      - name: Terraform init
        run: terraform init
      
      # - name: antonbabenko/pre-commit-terraform
      #   uses: antonbabenko/pre-commit-terraform@v1.79.1
      #   with:
      #     hooks: terraform_fmt, terraform_tflint, terraform_validate, terraform_providers_lock, checkov, terrascan, terraform_tfsec
      
      - name: Terraform show
        run: terraform show -no-color 

      - name: Install infracost
        run: sudo apt install infracost
      
      - name: Terraform infracost
        run: infracost breakdown --path=.