---
# .github/workflows/terraform.yaml
name: Terraform - Plan||Apply
run-name: '[${{ github.event_name }} - ${{ github.ref_name }}] Terraform executed by @${{ github.actor }}'

on:
  pull_request:
    branches:
      - main
env:
  terraformVersion: 1.3.6
  terraformWorkDir: ./terraform
  terraformModulesGithubOrg: terraform-aws-module-template
  awsRegion: us-east-1

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.terraformVersion }}

      - name: Terraform init
        run: terraform init
      
      - name: antonbabenko/pre-commit-terraform
        uses: antonbabenko/pre-commit-terraform@v1.74.1
        with:
          hooks: terraform_fmt, terraform_tflint, terraform_validate, terraform_providers_lock, checkov, terrascan, terraform_tfsec, infracost_breakdown, terraform_wrapper_module_for_each
      
      - name: Terraform show
        run: terraform show -no-color
      
      - name: Post Plan to GitHub PR
        if: steps.plan.outcome == 'success' && github.event_name == 'pull_request'
        uses: mshick/add-pr-comment@v2
        with:
          allow-repeats: true
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: github-actions[bot]
          message: |
            ## Terraform Plan
            ### Environment: ${{ github.base_ref }}
            ### Region: us-east-1
            ***Author***: `${{ github.actor }}` ***Action***: `${{ github.event_name }}`
            ***Working Directory***: `${{ env.terraformWorkDir }}`
            ***Workflow***: `${{ github.workflow }}`
            Please review below Terraform plan before accepting merge request:
            ```diff
            ${{ env.PLAN }}
            ```

      - name: Post Plan Failure
        if: steps.plan.outcome == 'failure'
        uses: mshick/add-pr-comment@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: github-actions[bot]
          message: |
            ## Terraform Plan
            ### Environment: ${{ github.base_ref }}
            ### Region: us-east-1
            ***Author***: `${{ github.actor }}` ***Action***: `${{ github.event_name }}`
            ***Working Directory***: `${{ env.terraformWorkDir }}`
            ***Workflow***: `${{ github.workflow }}`
            ```
            ${{ steps.plan.outputs.stderr }}
            ```
      
      - name: Stop pipeline if failed
        if: steps.plan.outcome == 'failure'
        run: exit 1

  plan_or_apply:
    name: Terraform Plan|Apply
    needs: lint
    runs-on: ubuntu-20.04


      